# Generated by Django 4.0.5 on 2022-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('card_name', models.CharField(max_length=50)),
                ('card_text', models.TextField()),
                ('thumbnail', models.URLField()),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Green/Yellow', 'Green and Yellow'), ('Green/Red', 'Green and Red'), ('GreenYellow', 'Green and Yellow'), ('Blue/Yellow', 'Blue and Yellow'), ('Blue/Green', 'Blue and Green'), ('Red/Yellow', 'Red and Yellow'), ('Red/Blue', 'Red and Blue')], max_length=50)),
                ('card_type', models.CharField(choices=[('Battle', 'Battle Card'), ('Unison', 'Unison Card'), ('Extra', 'Extra Card'), ('Leader', 'Leader Card')], max_length=50)),
                ('energy_cost', models.CharField(max_length=50)),
                ('special_trait', models.CharField(max_length=50)),
                ('power_card', models.CharField(max_length=50)),
                ('combo_power', models.IntegerField()),
                ('combo_energy', models.IntegerField()),
                ('era', models.CharField(max_length=50)),
                ('card_character', models.CharField(max_length=50)),
                ('card_url', models.URLField()),
                ('is_ultimate', models.IntegerField(default=0)),
                ('is_super_combo', models.IntegerField(default=0)),
                ('is_dragon_ball', models.IntegerField(default=0)),
                ('card_limit', models.IntegerField()),
                ('decks', models.ManyToManyField(to='card_checker.deck')),
            ],
            options={
                'ordering': ['card_number'],
            },
        ),
    ]
