# Generated by Django 4.0.5 on 2022-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_checker', '0002_alter_deck_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Green/Yellow', 'Green and Yellow'), ('Green/Red', 'Green and Red'), ('GreenYellow', 'Green and Yellow'), ('Blue/Yellow', 'Blue and Yellow'), ('Blue/Green', 'Blue and Green'), ('Red/Yellow', 'Red and Yellow'), ('Red/Blue', 'Red and Blue'), ('Red/Black', 'Red and Black')], max_length=50),
        ),
    ]
